name: Deploy NestJS to Huawei ECS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build on GitHub
        run: |
          cd nestjs-simple-api
          npm install
          npm run build

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. FORCE the server to use Node 18
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            # 2. Setup folders
            APP_DIR="/var/www/nestjs-api"
            RELEASE_DIR="$APP_DIR/releases/v${{ github.run_number }}"
            mkdir -p $RELEASE_DIR
            
            # 3. Get the code onto the server
            git clone https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git $RELEASE_DIR
            
            # 4. Build on the server
            cd $RELEASE_DIR/nestjs-simple-api
            npm install
            npm run build
            
            # 5. Link and Start
            ln -sfn $RELEASE_DIR/nestjs-simple-api $APP_DIR/current
            npm install -g pm2
            pm2 restart nestjs-api || pm2 start $APP_DIR/current/dist/main.js --name "nestjs-api"